### ISSUE TITLE
BLVD20KM Driver : Alarm LED (Red) blink & C-ERR LED (Red) illuminated

### ISSUE THREAD

**Issue by WsssM** [asukiaaa/BLVD20KM_asukiaaa#3]
Hello, It's me again, 

I modified the sketch as shown ;
```
#include <BLVD20KM_asukiaaa.h>
#define RS485_DE 4
#define RS485_RE RS485_DE
#define MOTOR_ADDRESS 0
```
I did the wiring betwen my Arduino Mega 2560, my Uart to RS485 Transceiver (https://www.sparkfun.com/products/10124) and my BLVD20KM Driver as follows:
```
Arduino <-> Uart to RS485 <-> LVD20KM
None <-> A <-> TR+ (LAN 3)
None <-> B <-> TR- (LAN 6)
None <-> GND <-> GND (LAN 2)
TX1 <-> RX-I <-> None
RX1 <-> TX-0 <-> None
D4 <-> RTS <-> None
5V <-> 3-5V <-> None
GND <-> GND <-> None
```

I set the switch 2 like this :
```
No	State
1	OFF
2	OFF
3	ON
4	OFF
5	ON
6	OFF
7	OFF
8	OFF
And switch 3 to 0
```

But I still have in the driver :
Alarm LED (Red) blinking
C-ERR LED (Red) illuminated
And the Serial Monitor :
Cannot read speed
Cannot read alarm

I hope you can find my mistake 

Thanks again
WsssM
![Arduino Mega](https://user-images.githubusercontent.com/68170072/143660160-b2f08e69-9160-44f3-a9c5-499aeccee0f4.jpg)
![BLVD20KM](https://user-images.githubusercontent.com/68170072/143660161-3eabc1fd-baba-4b90-b488-bf33fba6ef1e.jpg)

**Comment by asukiaaa** [comment]
Hello, can you try this?

Turn on 7 of Switch2
Because your RS485 chain seems end at the motor driver

Use address 1 for communication
Address 0 is udp communication so if you want to read information from some driver, using address 1 or more is required.
To use address 1, turn switch3 to 1 then change address on code.
```cpp
#define MOTOR_ADDRESS 1
```

How about these approach?

**Comment by WsssM** [comment]
Hi,
	Thanks again for your answer, I did all this but unfortunately the result remains the same, always (Alarm LED (Red) blink & C-ERR LED (Red) illuminated)

**Sketch :**
```
#define RS485_DE 4
#define RS485_RE RS485_DE // you can unify DE and RE
#define MOTOR_ADDRESS 1 // 0 for udp
...
```

**SW2 & SW3 (See picture below) :**
![SW2 SW3](https://user-images.githubusercontent.com/68170072/143770765-c82cd652-d6ce-4d3b-bc28-044d34278fd9.jpg)

I have already checked cables, and changed the SparkFun Transceiver Breakout, and the BLVD20KM driver to check if the problem comes from one of them but the problem remains the same.

I hope you find other ways to solve this problem.

**Comment by asukiaaa** [comment]
You may connect RX1 to RX-I and TX1 to TX-O but that's wrong
Connect RX1 to TX-O and TX1 to RX-I.
![Screenshot from 2021-11-30 15-58-10](https://user-images.githubusercontent.com/5975178/144000674-7c557d5a-9bf8-4b63-9b37-1fc861030e9d.png)
![Screenshot from 2021-11-30 15-58-54](https://user-images.githubusercontent.com/5975178/144000666-4eb51fce-576a-4ba0-b78c-823f4cb48b40.png)
![Screenshot from 2021-11-30 16-03-41](https://user-images.githubusercontent.com/5975178/144001132-2dd98d1e-4787-40fb-87d3-b8bed74722ff.png)

**Comment by WsssM** [comment]
Hi,
Great, I no longer have red lights, juste beautiful green :-D

![BLVD20KM_OK](https://user-images.githubusercontent.com/68170072/144328185-8fd07cb0-5157-445d-bb9d-4f08c2bf44f2.jpg)

Only the motor isn't running, and I think it should run a bit forward and a bit backward with your sketch

![BLVM620K-GFS](https://user-images.githubusercontent.com/68170072/144327875-9a5ef48b-aa4d-4cc6-a5df-affe330f2fac.jpg)

and I still have on my serial monitor the messages:
```
Cannot read alarm
Cannot read speed
```

**Comment by asukiaaa** [comment]
Does this green led bright at communicating?
If not, it seems not communicating.
![specify_green_led_on_rj45_juck](https://user-images.githubusercontent.com/5975178/144547635-c27cf9b5-1d55-4fd0-b822-60a3e63b3012.png)

I released 1.2.0 so can you update it and try with new example code?

**Comment by WsssM** [comment]
**_Does this green led bright at communicating?_**
No, the green led is off
**_I released 1.2.0 so can you update it and try with new example code?_**
I tried with the last version 1.2.1 but the compilation is blocked with the following error messages;
```
Arduino: 1.8.16 (Windows Store 1.8.51.0) (Windows 10), Board: "Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"
C:\Users\...\Arduino\libraries\BLVD20KM_asukiaaa\src\BLVD20KM_asukiaaa.cpp: In member function 'void BLVD20KM_asukiaaa::begin(long unsigned int, long unsigned int)':
C:\Users\...\Arduino\libraries\BLVD20KM_asukiaaa\src\BLVD20KM_asukiaaa.cpp:58:11: error: 'class rs485_asukiaaa::ModbusRtu::Central' has no member named 'msSilentInterval'
   modbus->msSilentInterval = baudrate <= 9600 ? 6 : 4;
           ^~~~~~~~~~~~~~~~
C:\Users\...\Arduino\libraries\BLVD20KM_asukiaaa\src\BLVD20KM_asukiaaa.cpp: In static member function 'static String BLVD20KM_asukiaaa::getStrOfError(uint8_t)':
C:\Users\...\Arduino\libraries\BLVD20KM_asukiaaa\src\BLVD20KM_asukiaaa.cpp:293:37: error: 'getStrOfError' is not a member of 'rs485_asukiaaa::ModbusRtu'
   return rs485_asukiaaa::ModbusRtu::getStrOfError(
                                     ^~~~~~~~~~~~~
exit status 1
Error compiling for board Arduino Mega or Mega 2560.
This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

```

**Comment by asukiaaa** [comment]
Can you try with updating `rs485_asukiaaa`?
This library depends on that lib but library manager seems not update that.

**Comment by WsssM** [comment]
I updated rs485_asukiaaa and I don't have compilation problem any more, but the green light still not blinking and I have this message in the serial monitor:
```
Cannot read alarm. E:11 no response
Cannot read speed. E:11 no response
Cannot read alarm. E:15 short data len
```

I also tried to connect the Arduino GND to the Driver GND to the LAN cable GND but I still have the same problem

**Comment by asukiaaa** [comment]
I tried some combination of connections with running example program.

- All OK: green led turns on
- RX and TX are connected with wrong pair: red led turns on
- RX and TX are not connected but DE and RE are connected: red led turns on
- A+ and B- are connected with wrong pair: red led turns on
- A+ and B- are not connected: no led turns on

In this case, I see LEDs on RJ45 jack.

I want you to check connection between LAN cable and RS485 module.
- LAN2: GND
- LAN3: A+
- LAN6: B-

![IMG_20211204_213551](https://user-images.githubusercontent.com/5975178/144709641-31388c2c-1604-4309-b396-8f94a747f2cc.jpg)
![IMG_20211204_213524](https://user-images.githubusercontent.com/5975178/144709642-9d7f053d-dfe6-4fc1-ac64-0c4e54ddd5ed.jpg)
![IMG_20211204_213239](https://user-images.githubusercontent.com/5975178/144709644-f3b5f954-98d5-443d-b4f9-50f3fe888910.jpg)

**Comment by WsssM** [comment]
Ourika, it finally works, and it's great.
![ok](https://user-images.githubusercontent.com/68170072/144724246-38c874b9-408a-4417-827c-289f517bb4ed.jpg)
and I see my motor running for the first time
For the origin of the problem I was going to say that it was my card that was broken because the problem was solved when I replaced it, but finally even when I returned to the original card it still works , I don't know what to say, I think it was a connection problem somewhere.
Anyway, thank you again for your assistance,
I will focus now on the control of 2 motors with my 2 BLVD20KM drivers

**Comment by asukiaaa** [comment]
> it finally works, and it's great.

I'm glad to know that.

I suggest you to use common modbus instance when you use multiple driver class.
I add a example about it as version 1.2.2.
https://github.com/asukiaaa/BLVD20KM_asukiaaa/blob/master/examples/ControlMultiple/ControlMultiple.ino

**Comment by WsssM** [comment]
Great, I'll start right away with this example. thanks again 🥇
